//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "BlinkyVB.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_BlinkyVB =
{
    "BlinkyVB", 
    0x0AAD7E0C,
    method_lookup
};

