//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "B1.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_B1 =
{
    "B1", 
    0xBB47C1F5,
    method_lookup
};

