//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "rgb_new.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_rgb_new =
{
    "rgb_new", 
    0xBB47C1F5,
    method_lookup
};

