//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _RGB_NEW_H_
#define _RGB_NEW_H_

#include <TinyCLR_Interop.h>


extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_rgb_new;

#endif  //_RGB_NEW_H_
