//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _TEST47_H_
#define _TEST47_H_

#include <TinyCLR_Interop.h>


extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Test47;

#endif  //_TEST47_H_
